### ISSUE TITLE
Uptrace v1.4.0 planning

### ISSUE THREAD

**Issue by vmihailenco** [uptrace/uptrace#177]
TODO

- [x] Finish feat: add site.path https://github.com/uptrace/uptrace/pull/159
- [x] Omit trace_id and time from spans_data.data column https://github.com/uptrace/uptrace/issues/168

Optional
- [ ] support letsencrypt https://github.com/uptrace/uptrace/issues/179

Taken by @vmihailenco:

- [x] Require PostgreSQL by default
- [x] Port all recent metrics improvements from https://github.com/uptrace/cloud-changelog/issues/11 WIP
- [x] Allow to import/export dashboards via YAML https://github.com/uptrace/uptrace/issues/157
- [x] Port [Alerts](https://app.uptrace.dev/alerting/1/alerts) from Uptrace Cloud

Check before release:
- Check https://github.com/uptrace/uptrace/issues/171

**Comment by afilp** [comment]
Will you be able to provide a simple (for v1) support for frontend stack logs?

Thanks!

**Comment by vmihailenco** [comment]
@afilp what are frontend stack logs? A link or a screenshot should be enough.

**Comment by afilp** [comment]
Thanks, please read here for more info (for start, we just need to catch the Javascript errors somewhere to view in almost real-time, also send with notifications/emails, etc.):

https://sentry.io/for/frontend/
https://docs.newrelic.com/docs/browser/browser-monitoring/getting-started/introduction-browser-monitoring/
https://www.datadoghq.com/blog/monitor-javascript-console-logs/

**Comment by vmihailenco** [comment]
The best option would be to add support for Sentry ingestion API so you can use sentry-javascript client with Uptrace. We have a prototype at https://github.com/uptrace/uptrace/pull/180

**Comment by afilp** [comment]
Do you think you will release this soon? Because we want to use logging for the backend and frontend, thanks a lot,
