### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by vmihailenco** [uptrace/uptrace#67]
- Metrics support using OpenTelemetry and Prometheus-like API
   - [x]  Accept OpenTelemetry metrics via OTLP and store in ClickHouse
   - [x]  Support AlertManager
   - [x]  Port Uptrace metrics
   - [x]  Do some thorough testing how Uptrace+Prometheus+AlertManager work together
   - [x]  Documentation
- [x] Allow to pin attributes on the overview page - https://github.com/uptrace/uptrace/issues/25
- [x] Search via AppBar

Stage 2

- [ ] Add latest queries history
- [ ] Allow to edit YAML configs (uptrace, prometheus, and alertmanager) from Uptrace UI

Optional / late stage

- [ ] Display & manage Prometheus Alerts from Uptrace UI
- [ ] Add a Service Map
